version: 2

sources:
  - name: northwind0611
    schema: northwind0611
    description: Fonte dos dados da Northwind
    tables:
      - name: orders
      - name: order_details
      - name: products
      - name: shippers
      - name: employees
      - name: customers
      - name: suppliers